### ISSUE TITLE
Error creating account.

### ISSUE THREAD

**Issue by robh007** [pepperize/cdk-organizations#299]
Hi, 

Not sure if I'm doing something wrong, but I seem to hit this error when creating an account. I use the following python CDK code. 

```python
# The code that defines your stack goes here
        create_account = Account(self, "Account",
                                 account_name="Account01",
                                 email="account01@domain.com",
                                 iam_user_access_to_billing=IamUserAccessToBilling.ALLOW,
                                 role_name="OrgRoleName"
                                 )
```

Which results in the following request to the custom lambda function.
```json
2022-04-21T10:59:29.241Z	603e7cfe-5e38-420c-9ce8-383aad35bfe0	INFO	Payload: {
    "RequestType": "Create",
    "ServiceToken": "arn:aws:lambda:us-east-1:123456789012:function:cdk-example-dev-Accountcd-ProviderframeworkonEvent-yIMmO8WFRe32",
    "StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/cdk-example-dev/bf969cb0-c161-11ec-9c1f-0a6e6428d797",
    "RequestId": "2a55e9ad-46c0-463a-acec-943a004201f7",
    "LogicalResourceId": "AccountCreateAccount833709C2",
    "ResourceType": "Custom::Organizations_Account",
    "ResourceProperties": {
        "ServiceToken": "arn:aws:lambda:us-east-1:123456789012:function:cdk-example-dev-Accountcd-ProviderframeworkonEvent-yIMmO8WFRe32",
        "RoleName": "OrganizationAccountAccessRole",
        "IamUserAccessToBilling": "ALLOW",
        "Email": "account001@domain.com",
        "ImportOnDuplicate": "true",
        "RemovalPolicy": "retain",
        "AccountName": “account001”
    },
    "PhysicalResourceId": "637860476275",
    "Data": {
        "ServiceToken": "arn:aws:lambda:us-east-1:123456789012:function:cdk-example-dev-Accountcd-ProviderframeworkonEvent-yIMmO8WFRe32",
        "RoleName": "OrganizationAccountAccessRole",
        "IamUserAccessToBilling": "ALLOW",
        "Email": “account001@domain.com”,
        "ImportOnDuplicate": "true",
        "RemovalPolicy": "retain",
        "AccountName": "Vend001",
        "AccountId": "123456789012"
    }
}
```

Then I receive the following error message.

```json
2022-04-21T10:59:29.300Z	603e7cfe-5e38-420c-9ce8-383aad35bfe0	ERROR	Invoke Error 	{
    "errorType": "MissingRequiredParameter",
    "errorMessage": "Missing required key 'CreateAccountRequestId' in params",
    "code": "MissingRequiredParameter",
    "message": "Missing required key 'CreateAccountRequestId' in params",
    "time": "2022-04-21T10:59:29.263Z",
    "stack": [
        "MissingRequiredParameter: Missing required key 'CreateAccountRequestId' in params",
        "    at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37)",
        "    at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:61:14)",
        "    at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:88:21)",
        "    at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10)",
        "    at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:132:42)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:96:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:86:9",
        "    at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:396:7)",
        "    at /var/runtime/node_modules/aws-sdk/lib/config.js:414:9"
    ]
}
```

I've also tried used the type script example & I receive the same error in the custom lambda functions. Any ideas?

**Comment by pflorek** [comment]
Which version are you using?

**Comment by pflorek** [comment]
@robh007 I guess, you are using a version higher than [0.1.0](https://github.com/pepperize/cdk-organizations/releases/tag/v0.1.0). If `ImportOnDuplicate` is set true, the `on-event-handler` will look for an existing account by the given email. If an account is found, then the API call to `createAccount` is skipped and `event.Data.CreateAccountRequestId` is undefined. Therefore I move the `ImportOnDuplicate` logic to the `is-complete-handler`

**Comment by robh007** [comment]
Thanks @pflorek - sorry I didn't get back to you sooner.

**Comment by pflorek** [comment]
@robh007 I hope it's also running smooth on your side now
