### ISSUE TITLE
Issue during CreateAccount stack creation: ...conflicts with another attempt to modify the same entity.

### ISSUE THREAD

**Issue by coltenkrauter** [pepperize/cdk-organizations#581]
## Context

The first time I deployed, I got an error that the name of the account stack was too long so it failed. So, I shortened the name and then deployed again. 

## Problem

Now, when I deploy, I am getting this error,

```
Received response status [FAILED] from custom resource. Message returned: AWS Organizations can't complete your request 
because it conflicts with another attempt to modify the same entity. Try again later. Logs: /aws/lambda/VeniceOrganization-
cdkorg-OnEventHandlerFunctionA6-TpNOToAkuuoW at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol
/json.js:52:27) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at Request.emit 
(/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/var/runtime/node_modules/aws-sdk/lib
/request.js:686:14) at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo 
(/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12) at /var/runtime/node_modules
/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) at 
Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) at Request.callListeners (/var/runtime
/node_modules/aws-sdk/lib/sequential_executor.js:116:18) (RequestId: 71de1dae-1e33-4c17-92f3-bc917ce36630)
```

<img width="1307" alt="Screen Shot 2022-08-30 at 10 15 59 AM" src="https://user-images.githubusercontent.com/18080897/187489474-eebbea39-85e2-4416-87a1-546c33f38972.png">

I tried deploying about 12 hours ago when I first got this error. I figured I would wait and try again later. So I just tried deploying and I am getting this again. 

Finally, I deleted all of the stacks except for the `CDKToolkit` and then tried deploying again and I still got this error.

Any idea why this is happening and how it can be resolved?

**Comment by pflorek** [comment]
Hey @coltenkrauter ,

which resource is throwing the error (account)? What are the props passed to it? Was the account created? Some props are already validated: https://github.com/pepperize/cdk-organizations/blob/main/src/validators.ts and the CDK should not deploy on validation error.

For conflicting errors, the Organizations API is not able to deploy some resources like account in parallel. Currently the solution is to manually create the sequential chain of the construct tree by using `node.addDependency()` https://github.com/pepperize/cdk-organizations/issues/447 An aspect that helps with that is currently work in progress https://github.com/pepperize/cdk-organizations/pull/547

**Comment by coltenkrauter** [comment]
Oh, interesting about creating accounts in parallel. That is likely the issue.

Yes, the accounts did end up getting created, but the script always ends in failure, which is not ideal.

Here is my code, 

```typescript
import { Account, Organization, OrganizationalUnit } from '@pepperize/cdk-organizations';
import { Construct } from 'constructs';
import { Stack } from 'aws-cdk-lib';

export class OrganizationStack extends Stack {
  constructor(scope: Construct, id: string, props: {}) {
    super(scope, id, props);

    interface organizationConfig {
      organizationalUnitName: string;
      projectNames: string[];
    }
    const organizationConfig: organizationConfig[] = [
      {
        organizationalUnitName: 'internal',
        projectNames: [
          'project4',
          'florence',
        ],
      },
      {
        organizationalUnitName: 'external',
        projectNames: [
          'project1',
          'project2',
          'project3',
        ],
      },
    ]

    // Create your organization
    const organization = new Organization(this, 'Organization', {});

    organizationConfig.forEach((organizationalUnit) => {
      // Create an organizational unit (OU)
      const organizationUnit = new OrganizationalUnit(this, `OrganizationalUnit${organizationalUnit.organizationalUnitName}`, {
        organizationalUnitName: organizationalUnit.organizationalUnitName,
        parent: organization.root,
      });  
      
      organizationalUnit.projectNames.forEach((projectName) => {
        // Create an account
        new Account(this, projectName, {
          accountName: projectName,
          email: `redacted+project-${projectName}@redacted.com`,
          parent: organizationUnit,
        });
      });
    });
  }
}
```

**Comment by pflorek** [comment]
Great idea of OrganizationConfig.

Just let's add a pointer to the previous organization resource.

```typescript
import { Account, Organization, OrganizationalUnit } from '@pepperize/cdk-organizations';
import { Construct } from 'constructs';
import { Stack } from 'aws-cdk-lib';

export class OrganizationStack extends Stack {
  constructor(scope: Construct, id: string, props: {}) {
    super(scope, id, props);

    interface organizationConfig {
      organizationalUnitName: string;
      projectNames: string[];
    }
    const organizationConfig: organizationConfig[] = [
      {
        organizationalUnitName: 'internal',
        projectNames: [
          'project4',
          'florence',
        ],
      },
      {
        organizationalUnitName: 'external',
        projectNames: [
          'project1',
          'project2',
          'project3',
        ],
      },
    ]

    // Create your organization
    const organization = new Organization(this, 'Organization', {});

    // Sequential chain resources
   let previous: Construct = organization.root;

    organizationConfig.forEach((organizationalUnit) => {
      // Create an organizational unit (OU)
      const organizationUnit = new OrganizationalUnit(this, `OrganizationalUnit${organizationalUnit.organizationalUnitName}`, {
        organizationalUnitName: organizationalUnit.organizationalUnitName,
        parent: organization.root,
      });  
      organizationUnit.node.addDependency(previous);
      previous= organizationUnit;
      
      organizationalUnit.projectNames.forEach((projectName) => {
        // Create an account
        const account= new Account(this, projectName, {
          accountName: projectName,
          email: `redacted+project-${projectName}@redacted.com`,
          parent: organizationUnit,
        });
        account.node.addDependency(previous);
        previous=account;
      });
    });
  }
}
```

https://docs.aws.amazon.com/cdk/api/v1/docs/core-readme.html#construct-dependencies

**Comment by coltenkrauter** [comment]
Ah, perfect. This worked like a charm. Thanks! I am deployed.

**Comment by pflorek** [comment]
🥰
